"""
phase1_agent.py
===============
Phase 1 worker: upstream protection-baseline synthesis via ASP optimisation.

This stage selects security and logging features subject to resource,
latency, and dual-risk budgets. Availability in Phase 1 follows the CIA
"A" definition: per-asset availability risk / DoS exposure in the
protected baseline, not operational resilience under fault scenarios.

Three strategy variants inject different objective modifications:
  max_security  â€” standard minimize (risk only)
  min_resources â€” lexicographic minimize: LUT usage, then tie-break on risk
  balanced      â€” lexicographic minimize: weighted total risk, then LUT usage
"""

from __future__ import annotations

import os
import queue
from typing import List, Optional

from ..core.clingo_runner import ClingoRunner
from ..core.solution_parser import Phase1Result, SolutionParser
from ip_catalog.xilinx_ip_catalog import export_security_features_to_lp


# ---------------------------------------------------------------------------
# Strategy parameters
# ---------------------------------------------------------------------------

# Extra ASP injected per strategy (appended to extra_facts before solving)
STRATEGY_EXTRA: dict = {
    "max_security": "",   # use the existing #minimize in opt_*.lp unchanged

    "min_resources": (
        "% min_resources strategy: add secondary LUT objective\n"
        "#minimize { LUTs@2, total : total_luts_used(LUTs) }.\n"
    ),

    "balanced": (
        "% balanced strategy: explicit weighted-risk objective plus LUT tie-break\n"
        "total_weighted_risk_sum(R) :- R = #sum { WR, C, Asset, Action : weighted_risk(C, Asset, Action, WR) }.\n"
        "#show total_weighted_risk_sum/1.\n"
        "#minimize { R@2 : total_weighted_risk_sum(R) }.\n"
        "#minimize { L@1 : total_luts_used(L) }.\n"
    ),
}


class Phase1Agent:
    """
    Runs the Phase 1 DSE optimisation for a given strategy.

    Parameters
    ----------
    clingo_dir : str
        Absolute path to the Clingo/ directory.
    testcase_lp : str
        Absolute path to the instance .lp file (for example
        Clingo/tgt_system_tc9_inst.lp).
    strategy : str
        One of 'max_security', 'min_resources', 'balanced'.
    progress_queue : queue.Queue | None
        Thread-safe queue for progress messages.  None = silent.
    extra_instance_facts : str
        Additional ASP facts from the network editor (overrides testcase_lp
        when the user has modified the topology).
    timeout : int
        Per-solve timeout in seconds.
    """

    PHASE1_LP_NAMES = [
        "security_features_inst.lp",
        # Instance facts (component, asset, system_capability, etc.) come from
        # extra_instance_facts generated by ASPGenerator â€” no hardcoded instance file.
        "init_enc.lp",
        "opt_redundancy_generic_enc.lp",
        "opt_latency_enc.lp",
        "opt_power_enc.lp",
        "opt_resource_enc.lp",
        "bridge_enc.lp",
    ]

    def __init__(
        self,
        clingo_dir: str,
        testcase_lp: str,
        strategy: str = "max_security",
        progress_queue: Optional[queue.Queue] = None,
        extra_instance_facts: str = "",
        timeout: int = 60,
        strategy_overrides: Optional[dict] = None,
        solver_config: Optional[dict] = None,
    ) -> None:
        self.clingo_dir           = clingo_dir
        self.testcase_lp          = testcase_lp
        self.strategy             = strategy
        self.progress_queue       = progress_queue
        self.extra_instance_facts = extra_instance_facts
        self.timeout              = timeout
        self.strategy_overrides   = strategy_overrides  # optional override dict
        self.solver_config        = solver_config or {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(self) -> Phase1Result:
        """
        Execute Phase 1 and return a Phase1Result.

        Posts progress messages to progress_queue if provided.
        Never raises â€” returns a Phase1Result with satisfiable=False on error.
        """
        self._post(f"[Phase 1/{self.strategy}] Starting security DSE optimisation...")
        export_security_features_to_lp(os.path.join(self.clingo_dir, "security_features_inst.lp"))

        lp_files = self._build_lp_list()

        effective_extra_dict = self.strategy_overrides if self.strategy_overrides else STRATEGY_EXTRA
        strategy_extra = effective_extra_dict.get(self.strategy, "")

        extra = self.extra_instance_facts
        if strategy_extra:
            extra = (extra + "\n" if extra else "") + strategy_extra

        runner = self._make_runner(timeout=self.timeout)
        result_raw = runner.solve(
            lp_files=lp_files,
            extra_facts=extra,
            num_solutions=1,
            opt_mode="optN",
        )

        status = result_raw["status"]
        if status == "UNSAT":
            self._post(
                f"[Phase 1/{self.strategy}] UNSAT â€” constraints may be infeasible. "
                f"Trying fallback with relaxed risk cap..."
            )
            result_raw = self._try_relaxed(lp_files, extra)
            status = result_raw["status"]

        if status not in ("SAT",):
            self._post(
                f"[Phase 1/{self.strategy}] ERROR/TIMEOUT â€” {result_raw['message']}"
            )
            r = Phase1Result(strategy=self.strategy, satisfiable=False)
            return r

        r = SolutionParser.parse_phase1(result_raw["atoms"], strategy=self.strategy)
        r.satisfiable = True
        r.optimal     = True  # we accept last-optimal model from optN

        self._post(
            f"[Phase 1/{self.strategy}] Done â€” "
            f"Risk: {r.total_risk()}, "
            f"LUTs: {r.total_luts:,}, "
            f"Power: {r.total_power:,} mW"
        )
        return r

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_lp_list(self) -> List[str]:
        """Build the ordered list of .lp files for Phase 1."""
        files: List[str] = []
        # Instance file only when no extra_instance_facts (CLI / standalone mode).
        # When the GUI provides generated facts, they fully replace the instance file.
        if not self.extra_instance_facts and self.testcase_lp and os.path.isfile(self.testcase_lp):
            files.append(self.testcase_lp)
        for name in self.PHASE1_LP_NAMES:
            path = os.path.join(self.clingo_dir, name)
            if os.path.isfile(path):
                files.append(path)
            else:
                self._post(f"[Phase 1] WARNING: LP file not found: {path}")
        return files

    def _try_relaxed(self, lp_files: List[str], extra: str) -> dict:
        """
        Retry with relaxed dual-risk caps as a fallback.
        Overrides both max_security_risk and max_avail_risk with permissive
        values (500) so the hard constraints are effectively disabled.
        This handles cases where a tight cap is infeasible for the given topology.
        """
        relaxed_extra = (
            extra + "\n"
            "% Fallback: override risk caps with permissive values.\n"
            "system_capability(max_security_risk, 500).\n"
            "system_capability(max_avail_risk, 500).\n"
        )
        runner = self._make_runner(timeout=self.timeout)
        return runner.solve(
            lp_files=lp_files,
            extra_facts=relaxed_extra,
            num_solutions=1,
            opt_mode="optN",
        )

    def _post(self, msg: str) -> None:
        """Post a progress message to the queue (non-blocking)."""
        if self.progress_queue is not None:
            try:
                self.progress_queue.put_nowait(("INFO", msg))
            except queue.Full:
                pass

    def _make_runner(self, timeout: int) -> ClingoRunner:
        return ClingoRunner(
            timeout=timeout,
            threads=self.solver_config.get("clingo_threads"),
            parallel_mode=self.solver_config.get("clingo_parallel_mode"),
            configuration=self.solver_config.get("clingo_configuration"),
        )

