"""
phase1_agent.py
===============
Phase 1 worker: upstream protection-baseline synthesis via ASP optimisation.

This stage selects security and realtime-detection features subject to resource,
latency, and dual-risk budgets. Availability in Phase 1 follows the CIA
"A" definition: per-asset availability risk / DoS exposure in the
protected baseline, not operational resilience under fault scenarios.

For comparison runs, the ASP backend now accepts preprocessed candidate pairs
so Clingo reasons over the same reduced security/realtime choice space as the
math backend instead of grounding the raw cartesian product.

Three strategy variants inject different objective modifications:
  max_security  - standard minimize (risk only)
  min_resources - lexicographic minimize: LUT usage, then tie-break on risk
  balanced      - lexicographic minimize: weighted total risk, then LUT usage
"""

from __future__ import annotations

import os
import queue
import re
from itertools import product
from typing import Dict, List, Optional, Set, Tuple

from ..core.clingo_runner import ClingoRunner
from ..core.solution_parser import Phase1Result, SolutionParser
from ip_catalog.xilinx_ip_catalog import (
    EXPLOIT_FACTOR_MAP,
    EXPOSURE_VALUES,
    REALTIME_DETECTION_VALUES,
    REALTIME_FEATURE_EXPORT_ORDER,
    SECURITY_FEATURE_EXPORT_ORDER,
    export_security_features_to_lp,
    get_calibrated_estimate,
)


# ---------------------------------------------------------------------------
# Strategy parameters
# ---------------------------------------------------------------------------

# Extra ASP injected per strategy (appended to extra_facts before solving)
STRATEGY_EXTRA: dict = {
    "max_security": (
        "% max_security strategy: deterministic tie-breaks after weighted risk\n"
        "#minimize { L@-1 : total_luts_used(L) }.\n"
        "selection_rank_score(S) :- S = #sum { Score, C, P : selected_pair(C, P), pair_choice_score(C, P, Score) }.\n"
        "#show selection_rank_score/1.\n"
        "#minimize { S@-2 : selection_rank_score(S) }.\n"
    ),

    "min_resources": (
        "% min_resources strategy: add secondary LUT objective\n"
        "#minimize { LUTs@2, total : total_luts_used(LUTs) }.\n"
        "selection_rank_score(S) :- S = #sum { Score, C, P : selected_pair(C, P), pair_choice_score(C, P, Score) }.\n"
        "#show selection_rank_score/1.\n"
        "#minimize { S@-1 : selection_rank_score(S) }.\n"
    ),

    "balanced": (
        "% balanced strategy: explicit weighted-risk objective plus LUT tie-break\n"
        "total_weighted_risk_sum(R) :- R = #sum { WR, C, Asset, Action : weighted_risk(C, Asset, Action, WR) }.\n"
        "#show total_weighted_risk_sum/1.\n"
        "#minimize { R@2 : total_weighted_risk_sum(R) }.\n"
        "#minimize { L@1 : total_luts_used(L) }.\n"
        "selection_rank_score(S) :- S = #sum { Score, C, P : selected_pair(C, P), pair_choice_score(C, P, Score) }.\n"
        "#show selection_rank_score/1.\n"
        "#minimize { S@-1 : selection_rank_score(S) }.\n"
    ),
}


class Phase1Agent:
    """
    Runs the Phase 1 DSE optimisation for a given strategy.

    Parameters
    ----------
    clingo_dir : str
        Absolute path to the Clingo/ directory.
    testcase_lp : str
        Absolute path to the instance .lp file (for example
        Clingo/tgt_system_tc9_inst.lp).
    strategy : str
        One of 'max_security', 'min_resources', 'balanced'.
    progress_queue : queue.Queue | None
        Thread-safe queue for progress messages. None = silent.
    extra_instance_facts : str
        Additional ASP facts from the network editor (overrides testcase_lp
        when the user has modified the topology).
    timeout : int
        Per-solve timeout in seconds.
    """

    PHASE1_LP_NAMES = [
        "security_features_inst.lp",
        # Instance facts (component, asset, system_capability, etc.) come from
        # extra_instance_facts generated by ASPGenerator - no hardcoded instance file.
        "init_enc.lp",
        "opt_redundancy_generic_enc.lp",
        "opt_latency_enc.lp",
        "opt_power_enc.lp",
        "opt_resource_enc.lp",
        "bridge_enc.lp",
    ]

    _RESOURCES = ("luts", "ffs", "dsps", "lutram", "bram", "bufg", "power_cost")
    _RECEIVER_RE = re.compile(r"^receiver\(([^,()]+)\)\.$")
    _ASSET_RE = re.compile(r"^asset\(([^,()]+),\s*([^,()]+),\s*(read|write|avail)\)\.$")
    _IMPACT_RE = re.compile(r"^impact\(([^,()]+),\s*(read|write|avail),\s*(-?\d+)\)\.$")
    _LATENCY_RE = re.compile(r"^allowable_latency\(([^,()]+),\s*(read|write),\s*(-?\d+)\)\.$")
    _REDUNDANCY_RE = re.compile(r"^redundant_group\(([^,()]+),\s*([^,()]+)\)\.$")
    _SYSTEM_CAP_RE = re.compile(r"^system_capability\(([^,()]+),\s*(-?\d+)\)\.$")
    _EXPLOITABILITY_RE = re.compile(r"^exploitability\(([^,()]+),\s*(\d+)\)\.$")
    _RISK_WEIGHT_RE = re.compile(r"^risk_weight\(([^,()]+),\s*(\d+)\)\.$")
    _START_STATE = (-1, -1)

    def __init__(
        self,
        clingo_dir: str,
        testcase_lp: str,
        strategy: str = "max_security",
        progress_queue: Optional[queue.Queue] = None,
        extra_instance_facts: str = "",
        timeout: int = 60,
        strategy_overrides: Optional[dict] = None,
        solver_config: Optional[dict] = None,
    ) -> None:
        self.clingo_dir = clingo_dir
        self.testcase_lp = testcase_lp
        self.strategy = strategy
        self.progress_queue = progress_queue
        self.extra_instance_facts = extra_instance_facts
        self.timeout = timeout
        self.strategy_overrides = strategy_overrides
        self.solver_config = solver_config or {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(self) -> Phase1Result:
        """
        Execute Phase 1 and return a Phase1Result.

        Posts progress messages to progress_queue if provided.
        Never raises - returns a Phase1Result with satisfiable=False on error.
        """
        self._post(f"[Phase 1/{self.strategy}] Starting security DSE optimisation...")
        export_security_features_to_lp(os.path.join(self.clingo_dir, "security_features_inst.lp"))

        lp_files = self._build_lp_list()

        effective_extra_dict = self.strategy_overrides if self.strategy_overrides else STRATEGY_EXTRA
        strategy_extra = effective_extra_dict.get(self.strategy, "")

        extra = self.extra_instance_facts
        pair_facts, pair_error = self._build_candidate_pair_facts()
        if pair_error:
            self._post(f"[Phase 1/{self.strategy}] UNSAT - {pair_error}")
            return Phase1Result(strategy=self.strategy, satisfiable=False)
        if pair_facts:
            extra = (extra + "\n" if extra else "") + pair_facts
        if strategy_extra:
            extra = (extra + "\n" if extra else "") + strategy_extra

        runner = self._make_runner(timeout=self.timeout)
        result_raw = runner.solve(
            lp_files=lp_files,
            extra_facts=extra,
            num_solutions=1,
            opt_mode="opt",
        )

        status = result_raw["status"]
        if status == "UNSAT":
            self._post(f"[Phase 1/{self.strategy}] UNSAT - constraints are infeasible.")
            return Phase1Result(strategy=self.strategy, satisfiable=False)

        if status == "TIMEOUT" and result_raw.get("atoms"):
            self._post(
                f"[Phase 1/{self.strategy}] TIMEOUT - using best-so-far model from ASP. "
                f"{result_raw['message']}"
            )
            result = SolutionParser.parse_phase1(result_raw["atoms"], strategy=self.strategy)
            result.satisfiable = True
            result.optimal = False
            self._post(
                f"[Phase 1/{self.strategy}] Best-so-far - "
                f"Objective risk: {result.total_risk()}, "
                f"LUTs: {result.total_luts:,}, "
                f"Power: {result.total_power:,} mW"
            )
            return result

        if status != "SAT":
            self._post(f"[Phase 1/{self.strategy}] ERROR/TIMEOUT - {result_raw['message']}")
            return Phase1Result(strategy=self.strategy, satisfiable=False)

        result = SolutionParser.parse_phase1(result_raw["atoms"], strategy=self.strategy)
        result.satisfiable = True
        result.optimal = True

        self._post(
            f"[Phase 1/{self.strategy}] Done - "
            f"Objective risk: {result.total_risk()}, "
            f"LUTs: {result.total_luts:,}, "
            f"Power: {result.total_power:,} mW"
        )
        return result

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_lp_list(self) -> List[str]:
        """Build the ordered list of .lp files for Phase 1."""
        files: List[str] = []
        # Instance file only when no extra_instance_facts (CLI / standalone mode).
        # When the GUI provides generated facts, they fully replace the instance file.
        if not self.extra_instance_facts and self.testcase_lp and os.path.isfile(self.testcase_lp):
            files.append(self.testcase_lp)
        for name in self.PHASE1_LP_NAMES:
            path = os.path.join(self.clingo_dir, name)
            if os.path.isfile(path):
                files.append(path)
            else:
                self._post(f"[Phase 1] WARNING: LP file not found: {path}")
        return files

    def _build_candidate_pair_facts(self) -> Tuple[str, str]:
        """
        Precompute feasible security/realtime pairs per receiver.

        This mirrors the math backend's latency filtering, non-redundant
        security-risk cap filtering, and dominance pruning so the ASP backend
        compares against the same reduced search space instead of grounding the
        raw cartesian product.
        """
        instance_text = self._instance_facts_text()
        if not instance_text.strip():
            return "", ""

        parsed = self._parse_instance_facts(instance_text)
        receivers = parsed["receivers"]
        if not receivers:
            return "", ""

        grouped_components = parsed["grouped_components"]
        security_cap = parsed["system_caps"].get(
            "max_security_risk",
            parsed["system_caps"].get("max_asset_risk", 500),
        )

        pair_options = [
            (
                security,
                realtime,
                self._feature_latency(security) + self._feature_latency(realtime),
            )
            for security in SECURITY_FEATURE_EXPORT_ORDER
            for realtime in REALTIME_FEATURE_EXPORT_ORDER
        ]
        pair_risk_metric = {
            pair_index: int(EXPOSURE_VALUES[security]) * int(REALTIME_DETECTION_VALUES[realtime])
            for pair_index, (security, realtime, _latency) in enumerate(pair_options)
        }
        pair_resource_vectors = {
            pair_index: tuple(
                self._feature_cost(security, resource_name) + self._feature_cost(realtime, resource_name)
                for resource_name in self._RESOURCES
            )
            for pair_index, (security, realtime, _latency) in enumerate(pair_options)
        }

        feasible_pairs: Dict[str, List[int]] = {}

        for component in receivers:
            caps = parsed["latency_caps"].get(component, [("read", 1000)])
            rows = parsed["component_rows"].get(component, [])
            exploit_factor = EXPLOIT_FACTOR_MAP.get(parsed["exploitability"].get(component, 3), 10)
            feasible: List[int] = []
            for pair_index, (security, realtime, latency) in enumerate(pair_options):
                if any(latency > cap for _action, cap in caps):
                    continue
                if component not in grouped_components:
                    risk_rows = [
                        self._div_trunc_zero(
                            impact
                            * int(EXPOSURE_VALUES[security])
                            * int(REALTIME_DETECTION_VALUES[realtime])
                            * exploit_factor,
                            100,
                        )
                        for _asset, _action, impact in rows
                    ]
                    if any(risk > security_cap for risk in risk_rows):
                        continue
                feasible.append(pair_index)

            feasible = self._prune_pair_indices(feasible, pair_resource_vectors, pair_risk_metric)
            if not feasible:
                return "", f"no feasible Phase 1 feature pairs remain for component {component}"
            feasible_pairs[component] = feasible

        group_facts, group_error, group_plan_pair_indices = self._build_group_facts(
            parsed,
            feasible_pairs,
            pair_options,
            pair_resource_vectors,
        )
        if group_error:
            return "", group_error

        used_pair_indices: Set[int] = set(group_plan_pair_indices)
        for pair_indices in feasible_pairs.values():
            used_pair_indices.update(pair_indices)

        lines = ["% Preprocessed Phase 1 candidate pairs for ASP backend parity"]
        component_rank_weights = {
            component: len(receivers) - index
            for index, component in enumerate(receivers)
        }
        for pair_index in sorted(used_pair_indices):
            security, realtime, _latency = pair_options[pair_index]
            lines.append(f"pair_security({pair_index}, {security}).")
            lines.append(f"pair_realtime({pair_index}, {realtime}).")
        for component in receivers:
            for pair_index in feasible_pairs[component]:
                lines.append(
                    f"pair_choice_score({component}, {pair_index}, "
                    f"{component_rank_weights[component] * pair_index})."
                )
                if component in grouped_components:
                    continue
                lines.append(f"candidate_pair({component}, {pair_index}).")
        if group_facts:
            lines.append(group_facts)
        return "\n".join(lines), ""

    def _build_group_facts(
        self,
        parsed: Dict[str, object],
        feasible_pairs: Dict[str, List[int]],
        pair_options: List[Tuple[str, str, int]],
        pair_resource_vectors: Dict[int, Tuple[int, ...]],
    ) -> Tuple[str, str, Set[int]]:
        groups: List[Tuple[str, Tuple[str, ...]]] = parsed["groups"]  # type: ignore[assignment]
        if not groups:
            return "", "", set()

        combo_cap = parsed["system_caps"].get(  # type: ignore[index]
            "max_avail_risk",
            parsed["system_caps"].get("max_asset_risk", 500),  # type: ignore[index]
        )
        beta_pct = max(0, min(100, parsed["system_caps"].get("redundancy_beta_pct", 0)))  # type: ignore[index]
        risk_weights: Dict[str, int] = parsed["risk_weights"]  # type: ignore[assignment]
        lines = ["% Preprocessed redundancy-group plans for ASP backend parity"]
        used_pair_indices: Set[int] = set()

        for group_id, members in groups:
            if not members:
                continue

            final_state_cache: Dict[Tuple[int, int], Dict[str, object]] = {}
            nondominated_plans: List[Dict[str, object]] = []

            for combo in product(*(feasible_pairs[component] for component in members)):
                final_state = self._START_STATE
                resource_totals = [0] * len(self._RESOURCES)
                for pair_index in combo:
                    final_state = self._apply_group_pair_state(final_state, pair_options[pair_index])
                    resource_vector = pair_resource_vectors[pair_index]
                    for idx, value in enumerate(resource_vector):
                        resource_totals[idx] += value

                cached = final_state_cache.get(final_state)
                if cached is None:
                    rows = self._group_state_rows(members, final_state, parsed, beta_pct)
                    if any(
                        risk > combo_cap
                        for component_rows in rows.values()
                        for _asset, _action, risk in component_rows
                    ):
                        final_state_cache[final_state] = {"valid": False}
                        continue
                    weighted_risk = sum(
                        risk * risk_weights.get(asset_id, 1)
                        for component_rows in rows.values()
                        for asset_id, _action, risk in component_rows
                    )
                    cached = {
                        "valid": True,
                        "rows": rows,
                        "weighted_risk": weighted_risk,
                    }
                    final_state_cache[final_state] = cached

                if not cached["valid"]:
                    continue

                resource_tuple = tuple(resource_totals)
                weighted_risk = int(cached["weighted_risk"])
                if any(
                    self._plan_dominates(
                        existing["resources"],
                        existing["risk"],
                        existing["combo"],
                        resource_tuple,
                        weighted_risk,
                        combo,
                    )
                    for existing in nondominated_plans
                ):
                    continue

                nondominated_plans = [
                    existing
                    for existing in nondominated_plans
                    if not self._plan_dominates(
                        resource_tuple,
                        weighted_risk,
                        combo,
                        existing["resources"],
                        existing["risk"],
                        existing["combo"],
                    )
                ]
                nondominated_plans.append(
                    {
                        "combo": combo,
                        "resources": resource_tuple,
                        "risk": weighted_risk,
                        "rows": cached["rows"],
                    }
                )

            if not nondominated_plans:
                return "", f"no feasible redundancy selections remain for group {group_id}", set()

            for plan_index, plan in enumerate(nondominated_plans):
                combo = plan["combo"]
                lines.append(f"group_plan_candidate({group_id}, {plan_index}).")
                for component, pair_index in zip(members, combo):
                    used_pair_indices.add(pair_index)
                    lines.append(
                        f"group_plan_member_pair({group_id}, {plan_index}, {component}, {pair_index})."
                    )
                for component, rows in plan["rows"].items():
                    for asset_id, action, risk in rows:
                        lines.append(
                            f"group_plan_final_risk({group_id}, {plan_index}, {component}, {asset_id}, {action}, {risk})."
                        )

        return "\n".join(lines), "", used_pair_indices

    def _instance_facts_text(self) -> str:
        if self.extra_instance_facts.strip():
            return self.extra_instance_facts
        if self.testcase_lp and os.path.isfile(self.testcase_lp):
            with open(self.testcase_lp, "r", encoding="utf-8") as handle:
                return handle.read()
        return ""

    def _parse_instance_facts(self, text: str) -> Dict[str, object]:
        receivers: List[str] = []
        seen_receivers: Set[str] = set()
        asset_rows: List[Tuple[str, str, str]] = []
        impacts: Dict[Tuple[str, str], int] = {}
        latency_by_asset_action: Dict[Tuple[str, str], int] = {}
        grouped_components: Set[str] = set()
        group_members: Dict[str, List[str]] = {}
        system_caps: Dict[str, int] = {}
        exploitability: Dict[str, int] = {}
        risk_weights: Dict[str, int] = {}

        for raw_line in text.splitlines():
            line = raw_line.strip()
            if not line or line.startswith("%") or ":-" in line:
                continue

            match = self._RECEIVER_RE.match(line)
            if match:
                component = match.group(1)
                if component not in seen_receivers:
                    receivers.append(component)
                    seen_receivers.add(component)
                continue

            match = self._ASSET_RE.match(line)
            if match:
                asset_rows.append((match.group(1), match.group(2), match.group(3)))
                continue

            match = self._IMPACT_RE.match(line)
            if match:
                impacts[(match.group(1), match.group(2))] = int(match.group(3))
                continue

            match = self._LATENCY_RE.match(line)
            if match:
                latency_by_asset_action[(match.group(1), match.group(2))] = int(match.group(3))
                continue

            match = self._REDUNDANCY_RE.match(line)
            if match:
                group_id = match.group(1)
                component = match.group(2)
                grouped_components.add(component)
                group_members.setdefault(group_id, []).append(component)
                continue

            match = self._SYSTEM_CAP_RE.match(line)
            if match:
                system_caps[match.group(1)] = int(match.group(2))
                continue

            match = self._EXPLOITABILITY_RE.match(line)
            if match:
                exploitability[match.group(1)] = int(match.group(2))
                continue

            match = self._RISK_WEIGHT_RE.match(line)
            if match:
                risk_weights[match.group(1)] = int(match.group(2))

        component_rows: Dict[str, List[Tuple[str, str, int]]] = {}
        latency_caps: Dict[str, List[Tuple[str, int]]] = {}
        for component, asset_id, action in asset_rows:
            impact = impacts.get((asset_id, action))
            if impact is None:
                continue
            component_rows.setdefault(component, []).append((asset_id, action, impact))
            if action in ("read", "write"):
                latency_caps.setdefault(component, []).append(
                    (action, latency_by_asset_action.get((asset_id, action), 1000))
                )

        for component in receivers:
            if component not in latency_caps:
                latency_caps[component] = [("read", 1000)]
            exploitability.setdefault(component, 3)
        groups = [
            (group_id, tuple(sorted(dict.fromkeys(members))))
            for group_id, members in group_members.items()
        ]

        return {
            "receivers": receivers,
            "component_rows": component_rows,
            "latency_caps": latency_caps,
            "grouped_components": grouped_components,
            "groups": groups,
            "system_caps": system_caps,
            "exploitability": exploitability,
            "risk_weights": risk_weights,
        }

    def _feature_cost(self, feature: str, resource_name: str) -> int:
        estimate = get_calibrated_estimate(feature)
        attr_name = {
            "luts": "luts",
            "ffs": "ffs",
            "dsps": "dsps",
            "lutram": "lutrams",
            "bram": "brams",
            "bufg": "bufg",
            "power_cost": "power_mw",
        }.get(resource_name)
        if attr_name is None:
            return 0
        return int(round(getattr(estimate, attr_name, 0)))

    def _feature_latency(self, feature: str) -> int:
        return int(get_calibrated_estimate(feature).latency)

    def _apply_group_pair_state(
        self,
        prev_state: Tuple[int, int],
        pair: Tuple[str, str, int],
    ) -> Tuple[int, int]:
        normalized = self._pair_normalized_prob(pair)
        denormalized = self._pair_denormalized_prob(pair)
        if prev_state == self._START_STATE:
            return (normalized, denormalized)
        combined_norm = self._div_trunc_zero(prev_state[0] * normalized, 1000)
        return (combined_norm, max(prev_state[1], denormalized))

    def _pair_normalized_prob(self, pair: Tuple[str, str, int]) -> int:
        security, realtime, _latency = pair
        original_prob = int(EXPOSURE_VALUES[security]) * int(REALTIME_DETECTION_VALUES[realtime])
        return self._div_trunc_zero((original_prob - 25) * 1000, 975)

    def _pair_denormalized_prob(self, pair: Tuple[str, str, int]) -> int:
        return self._denormalize_prob(self._pair_normalized_prob(pair))

    def _denormalize_prob(self, normalized: int) -> int:
        return self._div_trunc_zero(normalized * 975, 1000) + 250

    def _group_state_rows(
        self,
        members: Tuple[str, ...],
        final_state: Tuple[int, int],
        parsed: Dict[str, object],
        beta_pct: int,
    ) -> Dict[str, List[Tuple[str, str, int]]]:
        component_rows: Dict[str, List[Tuple[str, str, int]]] = parsed["component_rows"]  # type: ignore[assignment]
        exploitability: Dict[str, int] = parsed["exploitability"]  # type: ignore[assignment]
        independent_denorm = self._denormalize_prob(final_state[0])
        denorm = self._div_trunc_zero(
            ((100 - beta_pct) * independent_denorm) + (beta_pct * final_state[1]),
            100,
        )
        rows_by_component: Dict[str, List[Tuple[str, str, int]]] = {}
        for component in members:
            exploit_factor = EXPLOIT_FACTOR_MAP.get(exploitability.get(component, 3), 10)
            rows: List[Tuple[str, str, int]] = []
            for asset_id, action, impact in component_rows.get(component, []):
                rows.append(
                    (
                        asset_id,
                        action,
                        self._div_trunc_zero(impact * denorm * exploit_factor, 1000),
                    )
                )
            rows_by_component[component] = rows
        return rows_by_component

    @staticmethod
    def _plan_dominates(
        lhs_resources: Tuple[int, ...],
        lhs_risk: int,
        lhs_combo: Tuple[int, ...],
        rhs_resources: Tuple[int, ...],
        rhs_risk: int,
        rhs_combo: Tuple[int, ...],
    ) -> bool:
        return (
            (
                all(lhs <= rhs for lhs, rhs in zip(lhs_resources, rhs_resources))
                and lhs_risk <= rhs_risk
                and (
                    any(lhs < rhs for lhs, rhs in zip(lhs_resources, rhs_resources))
                    or lhs_risk < rhs_risk
                )
            )
            or (
                lhs_resources == rhs_resources
                and lhs_risk == rhs_risk
                and lhs_combo < rhs_combo
            )
        )

    def _prune_pair_indices(
        self,
        pair_indices: List[int],
        pair_resource_vectors: Dict[int, Tuple[int, ...]],
        pair_risk_metric: Dict[int, int],
    ) -> List[int]:
        pruned: List[int] = []
        for pair_index in pair_indices:
            dominated = False
            for other_index in pair_indices:
                if other_index == pair_index:
                    continue
                other_resources = pair_resource_vectors[other_index]
                pair_resources = pair_resource_vectors[pair_index]
                if (
                    all(other <= current for other, current in zip(other_resources, pair_resources))
                    and pair_risk_metric[other_index] <= pair_risk_metric[pair_index]
                    and (
                        any(other < current for other, current in zip(other_resources, pair_resources))
                        or pair_risk_metric[other_index] < pair_risk_metric[pair_index]
                        or (
                            other_resources == pair_resources
                            and pair_risk_metric[other_index] == pair_risk_metric[pair_index]
                            and other_index < pair_index
                        )
                    )
                ):
                    dominated = True
                    break
            if not dominated:
                pruned.append(pair_index)
        return pruned

    def _post(self, msg: str) -> None:
        """Post a progress message to the queue (non-blocking)."""
        if self.progress_queue is not None:
            try:
                self.progress_queue.put_nowait(("INFO", msg))
            except queue.Full:
                pass

    def _make_runner(self, timeout: int) -> ClingoRunner:
        return ClingoRunner(
            timeout=timeout,
            threads=self.solver_config.get("clingo_threads"),
            parallel_mode=self.solver_config.get("clingo_parallel_mode", "compete"),
            configuration=self.solver_config.get("clingo_configuration", "jumpy"),
            opt_strategy=self.solver_config.get("clingo_opt_strategy", "usc"),
        )

    @staticmethod
    def _div_trunc_zero(numerator: int, denominator: int) -> int:
        """Match Clingo integer division semantics, which truncate toward zero."""
        if denominator == 0:
            raise ZeroDivisionError("denominator must be non-zero")
        quotient = abs(numerator) // abs(denominator)
        if (numerator < 0) ^ (denominator < 0):
            return -quotient
        return quotient
